#include <string>
#include <iostream>
#include <map>
#include <fstream>
#include <iomanip>
#include <vector>
#include <sstream>
#include <regex>

using std::cout;
using std::endl;
using std::string;
using std::map;
using std::regex;
using std::multimap;
using std::vector;
using std::ifstream;
using std::ofstream;
using std::setw;
using std::left;
using std::right;
