Zodis                             Kiekis
Dudley                                 5
Dursley                               11
Dursleys                               4
He                                     2
Mr                                     6
Mrs                                    8
Page                                   2
Potter                                 2
Potters                                4
The                                    4
They                                   2
a                                     11
about                                  2
and                                   13
as                                     6
away                                   2
be                                     3
because                                3
boy                                    2
but                                    4
called                                 2
didnt                                  4
for                                    3
had                                    6
have                                   2
he                                     3
her                                    3
his                                    5
if                                     2
in                                     5
into                                   2
it                                     3
large                                  2
much                                   2
mysterious                             2
neck                                   2
neighbors                              2
number                                 2
of                                     6
on                                     3
out                                    3
over                                   2
past                                   2
picked                                 2
say                                    2
she                                    3
sister                                 3
small                                  2
son                                    2
strange                                2
that                                   5
the                                   18
their                                  2
there                                  2
they                                   8
think                                  2
to                                     6
up                                     2
very                                   3
was                                   10
were                                   4
which                                  2
with                                   3
would                                  3
